name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  windows:
    runs-on: windows-latest

    env:
      SOLUTION_FILE_PATH: msvc15/e57parser.sln
      BUILD_CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: msvc/x64/Release/e57parser.exe


