name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  windows:
    runs-on: windows-latest

    env:
      SOLUTION_FILE_PATH: msvc/e57parser.sln
      BUILD_CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: msvc/x64/Release/e57parser.exe


  linux-gcc:
    runs-on: ubuntu-latest

    env:
      CXXFLAGS: -fms-extensions
      CFLAGS: -fms-extensions

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        cd make
        make

    - uses: actions/upload-artifact@v3
      with:
        name: linux-gcc-executable
        path: make/e57parser


  linux-clang:
    runs-on: ubuntu-latest

    env:
      CXX: clang++
      CC: clang

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        cd make
        make

    - uses: actions/upload-artifact@v3
      with:
        name: linux-clang-executable
        path: make/e57parser

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        cd make
        make

    - uses: actions/upload-artifact@v3
      with:
        name: macos-executable
        path: make/e57parser
